### ISSUE TITLE
Specify version of bolt to install based on testing of specific bolt with supported PE ranges

### ISSUE THREAD

**Issue by MartyEwings** [puppetlabs/puppetlabs-puppet_bolt_server#11]
https://github.com/puppetlabs/puppetlabs-puppet_bolt_server/blob/6b29aecc7965ac88e146fd752813a9ecef669755/manifests/init.pp#L20

The version of BOLT installed by this module should be locked to specific version number, at this time this will install "latest" as to when the module is deployed.

The version in major releases should be tied to what was tested against the PE version(s) the module supports

**Comment by mcka1n** [comment]
Good catch @MartyEwings 

I made the change and now we are locking the Bolt version on this PR https://github.com/puppetlabs/puppetlabs-puppet_bolt_server/pull/15

Thanks!

**Comment by mcka1n** [comment]
Closing this ticket because PR #15 was approved and merged
