### ISSUE TITLE
Puppet version requirement should be tighter

### ISSUE THREAD

**Issue by MartyEwings** [puppetlabs/puppetlabs-puppet_bolt_server#12]
https://github.com/puppetlabs/puppetlabs-puppet_bolt_server/blob/6b29aecc7965ac88e146fd752813a9ecef669755/metadata.json#L55

The version of puppet this supports should be set as tightly as possible to line up with the PE versions the module supports, this will prevent deployment by customers on unsupported PE versions, and indeed untested PE versions.

Bottom of this bounding should likey be no less than the LTS puppet version, and the upper limit should only be what has been tested explicitly, IE we don't want customers deploying on 2023.1 if we have never tested this on puppet 8.x

**Comment by mcka1n** [comment]
Thanks again @MartyEwings for the suggestion.

I made the change on this PR https://github.com/puppetlabs/puppetlabs-puppet_bolt_server/pull/15
